# Generated by Django 4.2.3 on 2023-07-06 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0003_alter_customuser_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
