# Generated by Django 4.2.3 on 2023-07-11 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0006_userprofiles_delete_profiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofiles',
            name='created_at',
        ),
    ]
