# Generated by Django 4.2.3 on 2023-07-11 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0008_userprofiles_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofiles',
            name='created_at',
        ),
    ]
