# Generated by Django 4.2.3 on 2023-07-11 04:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0009_remove_userprofiles_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
