# Generated by Django 4.2.3 on 2023-07-11 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0010_userprofiles_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
